server:
  port: 8072

eazybank:
  gateway:
    message-uri: ${EAZYBANK_GATEWAY_MESSAGE_URI:http://localhost:9010}
    configserver-uri: ${EAZYBANK_GATEWAY_CONFIGSERVER_URI:http://localhost:8071}

spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls-primary-name: accounts
    urls:
      - name: accounts
        url: /eazybank/accounts/v3/api-docs
      - name: cards
        url: /eazybank/cards/v3/api-docs
      - name: loans
        url: /eazybank/loans/v3/api-docs
      - name: message
        url: /eazybank/message/v3/api-docs
      - name: configserver
        url: /eazybank/configserver/v3/api-docs
      - name: gateway
        url: /v3/api-docs

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    root: INFO
    com.eazybytes.gatewayserver: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
